### ISSUE TITLE
get ottID from ncbi ID (or whatever)

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/taxomachine#118] opened 2015-12-01 19:16 UTC
Seems like a useful service would be to return an ottID from a given ncbi ID.

**Comment by mtholder** [comment] 2015-12-01 19:20
I agree it is a good idea. but I'm closing this because, I think this is a duplicate of https://github.com/OpenTreeOfLife/taxomachine/issues/97.

**Closed by mtholder** 2015-12-01 19:20 UTC

**Comment by josephwb** [comment] 2015-12-01 19:27
Thanks for catching that.
